---
apiVersion: v1
kind: Namespace
metadata:
  name: fault-tolerance
  labels:
    name: fault-tolerance
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speed-limit
  namespace: fault-tolerance
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      demo: daemonSet-fault-tolerance-speed-limit
  template:
    metadata:
      labels: 
        demo: daemonSet-fault-tolerance-speed-limit
    spec:
      initContainers:
      - args:
        - "10"
        image: mak3r/bandwidth:v0.1.0
        imagePullPolicy: IfNotPresent
        name: bw
      containers:
      - args:
        - run
        image: mak3r/network-load:v0.1.0
        imagePullPolicy: IfNotPresent
        name: throttle-example
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        readinessProbe:
          exec:
            command:
              - /usr/local/bin/readiness.sh
          initialDelaySeconds: 20
          periodSeconds: 5
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

